[package]
name = "rayt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.0"
rand = { version = "0.8.0", features = [ "small_rng" ] }
png = "0.17.7"
wavefront_obj = "10.0.0"
